version: '3.8'

services:
  redis:
    image: redis:7

  application:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: /start
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: /worker.start
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - application

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
      - application
      - worker
