"""init ads

Revision ID: 418f2c6fc6ff
Revises: 2d06ebab9286
Create Date: 2024-07-28 17:32:35.186163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418f2c6fc6ff'
down_revision: Union[str, None] = '2d06ebab9286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('header', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('author_link', sa.String(length=150), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
